# SPDX-License-Identifier: GPL-2.0-only
kirin9xx-drm-y := kirin9xx_drm_drv.o \
		  kirin9xx_drm_dss.o \
		  kirin9xx_drm_dpe_utils.o \
		  kirin970_defs.o kirin960_defs.o \
		  kirin9xx_drm_overlay_utils.o

obj-$(CONFIG_DRM_HISI_KIRIN9XX) += kirin9xx-drm.o kirin9xx_dw_drm_dsi.o kirin9xx_pwm.o
